name: Clever Cloud Review App

on:
  workflow_dispatch:
    inputs:
      action:
        description: "action"
        required: true
        default: d√©ploiement
        type: choice
        options:
          - deploy
          - update
          - delete
jobs:
  deploy:
    if: github.event.inputs.action == 'deploy'
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: read
    environment:
      name: review/${{ github.event.number }}
    steps:
      - run: echo "Le nom de la branche est ${{ github.ref_name }} et le nom du repository est ${{ github.repository }}"
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - run: echo "Le repository clon√© est ${{ github.repository }} a √©t√© clon√© dans le runner de GitHub"
      - run: echo "üöÄ Le workflow est pr√™t √† tester le code dans le runner"
      - run: |
          ls ${{ github.workspace }}
      - run: echo "Le statut du job est ${{ job.status }}"
      - name: Installation de clever-tools
        run: npm install -g clever-tools
      - name: Cr√©ation et deploiement de l'application sur Clever Cloud
        env:
          CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
          CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
          ORGA_ID: ${{ secrets.CLEVER_ORGA_ID }}
        run: |
          BRANCH_NAME="${{ github.ref_name }}"
          echo "Le nom de l'environnement est $BRANCH_NAME"
          if clever link -o "$ORGA_ID" "$BRANCH_NAME"; then
            echo "L'application $BRANCH_NAME existe d√©j√†. Annulation du d√©ploiement."
            exit 1
          else
            echo "Application $BRANCH_NAME en cours de cr√©ation."
            clever create --type node "$BRANCH_NAME" --alias "$BRANCH_NAME" --region par --org "$ORGA_ID"
            clever env set CC_NODE_BUILD_TOOL "custom" --alias "$BRANCH_NAME"
            clever env set CC_PRE_BUILD_HOOK "npm install -g pnpm" --alias "$BRANCH_NAME"
            clever env set CC_CUSTOM_BUILD_TOOL "pnpm install --prod && pnpm build" --alias "$BRANCH_NAME"
            clever domain add "$BRANCH_NAME.cleverapps.io" --alias "$BRANCH_NAME"
            clever deploy --alias "$BRANCH_NAME"
          fi
  update:
    if: github.event.inputs.action == 'update'
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: install clever-tools
        run: npm install -g clever-tools
      - name: Link and update app
        env:
          CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
          CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
          ORGA_ID: ${{ secrets.CLEVER_ORGA_ID }}
        run: |
          BRANCH_NAME="${{ github.ref_name }}"
          clever link -o "$ORGA_ID" "$BRANCH_NAME" || echo "Application $BRANCH_NAME not found, skipping link."
          clever deploy --alias "$BRANCH_NAME" --force
  delete:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    if: github.event.inputs.action == 'delete'
    steps:
      - name: install clever-tools
        run: npm install -g clever-tools
      - name: Supprimer l'application
        env:
          CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
          CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
          ORGA_ID: ${{ secrets.CLEVER_ORGA_ID }}
        run: |
          BRANCH_NAME="${{ github.ref_name }}"
          clever link -o "$ORGA_ID" "$BRANCH_NAME"
          clever delete --alias "$BRANCH_NAME" --yes
